### PR TITLE
Creating new filters (spam, flood and caps lock)

### PR DESCRIPTION
**Pull request by henriquemb**

### CODE REVIEW

**Comment by Luucx7** [comment]
Good, but every feature needs to be "modularized" and be able to be disabled, this one should be disabled by default.

**Comment by henriquemb** [comment]
Okay, I will make changes as requested.

**Comment by Luucx7** [comment]
Good, but both anti spam and anti flood needs specific settings on modules to activate/deactivate it.
You can add an boolean on filter.yml to setup this.

It is the core philosophy of the plugin being able to control everything it does.

Sorry for the _very_ late reply.

**Comment by MattCozendey** [comment]
cool bros

**Pull request merged**
